version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: purp_hotel_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_LOGIN=${MONGO_LOGIN}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=${MONGO_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    depends_on:
      - mongodb
    env_file:
      - .env.production
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb_hotel
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env.production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
